custom:
  site:                          # 운영 도메인으로 전환
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"

logging:
  level:
    root: INFO
    com.back: INFO