spring:
  application:
    name: snaptix

  datasource:
    url: jdbc:mysql://localhost:3306/snaptix?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: snaptix
    password: snaptix1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  exposed:
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      redis:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 80
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-failure-predicate: com.develop.snaptix.global.aop.aspect.RedisExceptionPredicate
        ignore-exceptions:
          - com.develop.snaptix.global.exception.BusinessException
